package apoocalipsis;
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup G_Inicio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        L_APOOCALIPSIS = new javax.swing.JLabel();
        L_Inicio = new javax.swing.JLabel();
        O_Retomar_Partida_Empezada = new javax.swing.JRadioButton();
        O_Crear_Nueva_Partida = new javax.swing.JRadioButton();
        B_Jugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));

        L_APOOCALIPSIS.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        L_APOOCALIPSIS.setForeground(new java.awt.Color(7, 33, 68));
        L_APOOCALIPSIS.setText("APOOCALIPSIS ZOMBIE");
        L_APOOCALIPSIS.setToolTipText("");

        L_Inicio.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        L_Inicio.setForeground(new java.awt.Color(7, 33, 68));
        L_Inicio.setText("Selecciona cómo quieres empezar la partida:");

        G_Inicio.add(O_Retomar_Partida_Empezada);
        O_Retomar_Partida_Empezada.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        O_Retomar_Partida_Empezada.setForeground(new java.awt.Color(7, 33, 68));
        O_Retomar_Partida_Empezada.setText("Retomar partida empezada");
        O_Retomar_Partida_Empezada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_Retomar_Partida_EmpezadaActionPerformed(evt);
            }
        });

        G_Inicio.add(O_Crear_Nueva_Partida);
        O_Crear_Nueva_Partida.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        O_Crear_Nueva_Partida.setForeground(new java.awt.Color(7, 33, 68));
        O_Crear_Nueva_Partida.setText("Crear nueva partida");
        O_Crear_Nueva_Partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_Crear_Nueva_PartidaActionPerformed(evt);
            }
        });

        B_Jugar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        B_Jugar.setForeground(new java.awt.Color(7, 33, 68));
        B_Jugar.setText("¡JUGAR!");
        B_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_JugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(L_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(B_Jugar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(O_Retomar_Partida_Empezada)
                            .addComponent(O_Crear_Nueva_Partida))))
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L_APOOCALIPSIS, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(408, 408, 408))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(L_APOOCALIPSIS)
                .addGap(91, 91, 91)
                .addComponent(L_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(O_Retomar_Partida_Empezada)
                .addGap(35, 35, 35)
                .addComponent(O_Crear_Nueva_Partida)
                .addGap(89, 89, 89)
                .addComponent(B_Jugar)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void O_Retomar_Partida_EmpezadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_Retomar_Partida_EmpezadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_Retomar_Partida_EmpezadaActionPerformed

    private void O_Crear_Nueva_PartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_Crear_Nueva_PartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_Crear_Nueva_PartidaActionPerformed

    private void B_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_JugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_JugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Jugar;
    private javax.swing.JLabel L_APOOCALIPSIS;
    private javax.swing.JLabel L_Inicio;
    private javax.swing.JRadioButton O_Crear_Nueva_Partida;
    private javax.swing.JRadioButton O_Retomar_Partida_Empezada;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
