package apoocalipsis;
/**
 *
 * @author Anass Chikou El Mahraoui, Edward Andrei, Manuel Alos de la Vega
 */
public class J_ConfirmacionZombiAislado extends javax.swing.JPanel {

    /**
     * Creates new form J_ConfirmacionZombiAislado
     */
    public J_ConfirmacionZombiAislado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_X = new javax.swing.JLabel();
        L_Y = new javax.swing.JLabel();
        L_DatosIntroducidos = new javax.swing.JLabel();
        L_Zombi = new javax.swing.JLabel();
        L_ConfirmacionY = new javax.swing.JLabel();
        L_ConfirmacionX = new javax.swing.JLabel();
        L_ConfirmacionZombi = new javax.swing.JLabel();
        L_LogoURJC = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 253, 253));

        L_X.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_X.setForeground(new java.awt.Color(7, 33, 68));
        L_X.setText("Coordenada X:");

        L_Y.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_Y.setForeground(new java.awt.Color(7, 33, 68));
        L_Y.setText("Coordenada Y:");

        L_DatosIntroducidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_DatosIntroducidos.setForeground(new java.awt.Color(7, 33, 68));
        L_DatosIntroducidos.setText("Datos introducidos:");

        L_Zombi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_Zombi.setForeground(new java.awt.Color(7, 33, 68));
        L_Zombi.setText("Tipo Zombi:");

        L_ConfirmacionY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionY.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionY.setText("jLabel1");

        L_ConfirmacionX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionX.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionX.setText("jLabel1");

        L_ConfirmacionZombi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionZombi.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionZombi.setText("jLabel1");

        L_LogoURJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apoocalipsis/image/URJ_simbolo_POS_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(L_Zombi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L_ConfirmacionZombi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L_X)
                        .addGap(18, 18, 18)
                        .addComponent(L_ConfirmacionX)
                        .addGap(126, 126, 126)
                        .addComponent(L_Y)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L_ConfirmacionY)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(L_DatosIntroducidos)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(L_LogoURJC)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(L_DatosIntroducidos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_X, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ConfirmacionX)
                    .addComponent(L_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ConfirmacionY))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Zombi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ConfirmacionZombi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_LogoURJC)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void escribirConfirmacion(int x, int y, String tipoZombi) {
        L_ConfirmacionX.setText(""+x);
        L_ConfirmacionY.setText(""+y);
        L_ConfirmacionZombi.setText(tipoZombi);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_ConfirmacionX;
    private javax.swing.JLabel L_ConfirmacionY;
    private javax.swing.JLabel L_ConfirmacionZombi;
    private javax.swing.JLabel L_DatosIntroducidos;
    private javax.swing.JLabel L_LogoURJC;
    private javax.swing.JLabel L_X;
    private javax.swing.JLabel L_Y;
    private javax.swing.JLabel L_Zombi;
    // End of variables declaration//GEN-END:variables
}
