package apoocalipsis;
public class J_ConfirmacionSimulacionAtaque extends javax.swing.JPanel {

    /**
     * Creates new form J_ConfirmacionSimulacionAtaque
     */
    public J_ConfirmacionSimulacionAtaque() {
        initComponents();
    }

    public void escribirConfirmacion(int xS, int yS, int xZ, int yZ, String tipoZombi, String nombreArma, int potenciaArma,
            int exitoArma, int alcanceArma, int dadosArma) {
        L_ConfirmacionArmaAlcance.setText(""+alcanceArma);
        L_ConfirmacionArmaDados.setText(""+dadosArma);
        L_ConfirmacionArmaExito.setText(""+exitoArma);
        L_ConfirmacionArmaNombre.setText(nombreArma);
        L_ConfirmacionArmaPotencia.setText(""+potenciaArma);
        L_ConfirmacionSuperX.setText(""+xS);
        L_ConfirmacionSuperY.setText(""+yS);
        L_ConfirmacionZombiTipo.setText(tipoZombi);
        L_ConfirmacionZombiX.setText(""+xZ);
        L_ConfirmacionZombiY.setText(""+yZ);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_NombreSuperviviente5 = new javax.swing.JLabel();
        L_NombreSuperviviente4 = new javax.swing.JLabel();
        L_NombreSuperviviente8 = new javax.swing.JLabel();
        L_NombreSuperviviente6 = new javax.swing.JLabel();
        L_NombreSuperviviente7 = new javax.swing.JLabel();
        L_NombreSuperviviente9 = new javax.swing.JLabel();
        L_NombreSuperviviente10 = new javax.swing.JLabel();
        L_NombreSuperviviente11 = new javax.swing.JLabel();
        L_NombreSuperviviente13 = new javax.swing.JLabel();
        L_NombreSuperviviente14 = new javax.swing.JLabel();
        L_NombreSuperviviente16 = new javax.swing.JLabel();
        L_NombreSuperviviente15 = new javax.swing.JLabel();
        L_NombreSuperviviente17 = new javax.swing.JLabel();
        L_NombreSuperviviente18 = new javax.swing.JLabel();
        L_ConfirmacionSuperX = new javax.swing.JLabel();
        L_ConfirmacionSuperY = new javax.swing.JLabel();
        L_ConfirmacionZombiY = new javax.swing.JLabel();
        L_ConfirmacionZombiX = new javax.swing.JLabel();
        L_ConfirmacionZombiTipo = new javax.swing.JLabel();
        L_ConfirmacionArmaNombre = new javax.swing.JLabel();
        L_ConfirmacionArmaAlcance = new javax.swing.JLabel();
        L_ConfirmacionArmaPotencia = new javax.swing.JLabel();
        L_ConfirmacionArmaDados = new javax.swing.JLabel();
        L_ConfirmacionArmaExito = new javax.swing.JLabel();
        L_LogoURJC = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 253, 253));

        L_NombreSuperviviente5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        L_NombreSuperviviente5.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente5.setText("Datos introducidos:");

        L_NombreSuperviviente4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente4.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente4.setText("Superviviente");

        L_NombreSuperviviente8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente8.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente8.setText("Zombi");

        L_NombreSuperviviente6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente6.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente6.setText("X:");

        L_NombreSuperviviente7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente7.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente7.setText("Y:");

        L_NombreSuperviviente9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente9.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente9.setText("X:");

        L_NombreSuperviviente10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente10.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente10.setText("Y:");

        L_NombreSuperviviente11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente11.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente11.setText("Tipo:");

        L_NombreSuperviviente13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente13.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente13.setText("Arma");

        L_NombreSuperviviente14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente14.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente14.setText("Nombre:");

        L_NombreSuperviviente16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente16.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente16.setText("Alcance:");

        L_NombreSuperviviente15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente15.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente15.setText("Potencia:");

        L_NombreSuperviviente17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente17.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente17.setText("Numero de dados:");

        L_NombreSuperviviente18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente18.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente18.setText("Valor de exito:");

        L_ConfirmacionSuperX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionSuperX.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionSuperX.setText("jLabel1");

        L_ConfirmacionSuperY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionSuperY.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionSuperY.setText("jLabel2");

        L_ConfirmacionZombiY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionZombiY.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionZombiY.setText("jLabel1");

        L_ConfirmacionZombiX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionZombiX.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionZombiX.setText("jLabel1");

        L_ConfirmacionZombiTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionZombiTipo.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionZombiTipo.setText("jLabel1");

        L_ConfirmacionArmaNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionArmaNombre.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionArmaNombre.setText("jLabel1");

        L_ConfirmacionArmaAlcance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionArmaAlcance.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionArmaAlcance.setText("jLabel1");

        L_ConfirmacionArmaPotencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionArmaPotencia.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionArmaPotencia.setText("jLabel1");

        L_ConfirmacionArmaDados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionArmaDados.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionArmaDados.setText("jLabel1");

        L_ConfirmacionArmaExito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L_ConfirmacionArmaExito.setForeground(new java.awt.Color(7, 33, 68));
        L_ConfirmacionArmaExito.setText("jLabel1");

        L_LogoURJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apoocalipsis/image/URJ_simbolo_POS_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(L_NombreSuperviviente14)
                                        .addComponent(L_NombreSuperviviente16))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(L_ConfirmacionArmaNombre)
                                        .addComponent(L_ConfirmacionArmaAlcance)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(135, 135, 135)
                                    .addComponent(L_NombreSuperviviente18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(L_NombreSuperviviente15)
                                                .addComponent(L_NombreSuperviviente17))
                                            .addGap(39, 39, 39)
                                            .addComponent(L_ConfirmacionArmaDados))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(L_ConfirmacionArmaExito)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_NombreSuperviviente4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(L_NombreSuperviviente7)
                                            .addComponent(L_NombreSuperviviente6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(L_ConfirmacionSuperY)
                                            .addComponent(L_ConfirmacionSuperX))))
                                .addGap(169, 169, 169)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_NombreSuperviviente9)
                                        .addGap(18, 18, 18)
                                        .addComponent(L_ConfirmacionZombiX)
                                        .addGap(57, 57, 57)
                                        .addComponent(L_NombreSuperviviente11))
                                    .addComponent(L_NombreSuperviviente8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_NombreSuperviviente10)
                                        .addGap(18, 18, 18)
                                        .addComponent(L_ConfirmacionZombiY))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(L_ConfirmacionArmaPotencia)))))
                        .addGap(18, 18, 18)
                        .addComponent(L_ConfirmacionZombiTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(L_NombreSuperviviente13)))
                .addGap(60, 71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(L_LogoURJC)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(L_NombreSuperviviente5)
                        .addGap(226, 226, 226))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(L_NombreSuperviviente5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_NombreSuperviviente6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_NombreSuperviviente9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_ConfirmacionSuperX)
                            .addComponent(L_ConfirmacionZombiX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_NombreSuperviviente7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_NombreSuperviviente10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_ConfirmacionZombiY)
                            .addComponent(L_ConfirmacionSuperY)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_NombreSuperviviente11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_ConfirmacionZombiTipo))))
                .addGap(70, 70, 70)
                .addComponent(L_NombreSuperviviente13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ConfirmacionArmaNombre)
                    .addComponent(L_ConfirmacionArmaPotencia))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ConfirmacionArmaAlcance)
                    .addComponent(L_ConfirmacionArmaDados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ConfirmacionArmaExito))
                .addGap(5, 5, 5)
                .addComponent(L_LogoURJC)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_ConfirmacionArmaAlcance;
    private javax.swing.JLabel L_ConfirmacionArmaDados;
    private javax.swing.JLabel L_ConfirmacionArmaExito;
    private javax.swing.JLabel L_ConfirmacionArmaNombre;
    private javax.swing.JLabel L_ConfirmacionArmaPotencia;
    private javax.swing.JLabel L_ConfirmacionSuperX;
    private javax.swing.JLabel L_ConfirmacionSuperY;
    private javax.swing.JLabel L_ConfirmacionZombiTipo;
    private javax.swing.JLabel L_ConfirmacionZombiX;
    private javax.swing.JLabel L_ConfirmacionZombiY;
    private javax.swing.JLabel L_LogoURJC;
    private javax.swing.JLabel L_NombreSuperviviente10;
    private javax.swing.JLabel L_NombreSuperviviente11;
    private javax.swing.JLabel L_NombreSuperviviente13;
    private javax.swing.JLabel L_NombreSuperviviente14;
    private javax.swing.JLabel L_NombreSuperviviente15;
    private javax.swing.JLabel L_NombreSuperviviente16;
    private javax.swing.JLabel L_NombreSuperviviente17;
    private javax.swing.JLabel L_NombreSuperviviente18;
    private javax.swing.JLabel L_NombreSuperviviente4;
    private javax.swing.JLabel L_NombreSuperviviente5;
    private javax.swing.JLabel L_NombreSuperviviente6;
    private javax.swing.JLabel L_NombreSuperviviente7;
    private javax.swing.JLabel L_NombreSuperviviente8;
    private javax.swing.JLabel L_NombreSuperviviente9;
    // End of variables declaration//GEN-END:variables
}
