package apoocalipsis;
public class J_ConfirmacionSupervivientes extends javax.swing.JPanel {
    private static final int TAM = 4;

    /**
     * Creates new form J_ConfirmacionSupervivientes
     */
    public J_ConfirmacionSupervivientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L_NombresSupervivientes = new javax.swing.JLabel();
        L_LogoURJC = new javax.swing.JLabel();
        L_NombreSuperviviente2 = new javax.swing.JLabel();
        L_NombreSuperviviente1 = new javax.swing.JLabel();
        L_NombreSuperviviente4 = new javax.swing.JLabel();
        L_NombreSuperviviente3 = new javax.swing.JLabel();
        L_Confirmacion2 = new javax.swing.JLabel();
        L_Confirmacion3 = new javax.swing.JLabel();
        L_Confirmacion4 = new javax.swing.JLabel();
        L_Confirmacion1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));

        L_NombresSupervivientes.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        L_NombresSupervivientes.setForeground(new java.awt.Color(7, 33, 68));
        L_NombresSupervivientes.setText("DATOS INTRODUCIDOS");

        L_LogoURJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apoocalipsis/image/URJ_simbolo_POS_1.png"))); // NOI18N

        L_NombreSuperviviente2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_NombreSuperviviente2.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente2.setText("Nombre Superviviente 2:");

        L_NombreSuperviviente1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_NombreSuperviviente1.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente1.setText("Nombre Superviviente 1:");

        L_NombreSuperviviente4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_NombreSuperviviente4.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente4.setText("Nombre Superviviente 4:");

        L_NombreSuperviviente3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_NombreSuperviviente3.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente3.setText("Nombre Superviviente 3:");

        L_Confirmacion2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_Confirmacion2.setForeground(new java.awt.Color(7, 33, 68));

        L_Confirmacion3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_Confirmacion3.setForeground(new java.awt.Color(7, 33, 68));

        L_Confirmacion4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_Confirmacion4.setForeground(new java.awt.Color(7, 33, 68));

        L_Confirmacion1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_Confirmacion1.setForeground(new java.awt.Color(7, 33, 68));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(461, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(L_LogoURJC)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente2)
                                .addGap(18, 18, 18)
                                .addComponent(L_Confirmacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente3)
                                .addGap(18, 18, 18)
                                .addComponent(L_Confirmacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente4)
                                .addGap(18, 18, 18)
                                .addComponent(L_Confirmacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente1)
                                .addGap(18, 18, 18)
                                .addComponent(L_Confirmacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(297, 297, 297))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(L_NombresSupervivientes)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(L_NombresSupervivientes)
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(L_NombreSuperviviente1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(L_Confirmacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Confirmacion2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Confirmacion3))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Confirmacion4)
                    .addComponent(L_NombreSuperviviente4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addComponent(L_LogoURJC)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void escribirConfirmacion(String[] arrayNombres) {
        L_Confirmacion1.setText(arrayNombres[0]);
        L_Confirmacion2.setText(arrayNombres[1]);
        L_Confirmacion3.setText(arrayNombres[2]);
        L_Confirmacion4.setText(arrayNombres[3]);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Confirmacion1;
    private javax.swing.JLabel L_Confirmacion2;
    private javax.swing.JLabel L_Confirmacion3;
    private javax.swing.JLabel L_Confirmacion4;
    private javax.swing.JLabel L_LogoURJC;
    private javax.swing.JLabel L_NombreSuperviviente1;
    private javax.swing.JLabel L_NombreSuperviviente2;
    private javax.swing.JLabel L_NombreSuperviviente3;
    private javax.swing.JLabel L_NombreSuperviviente4;
    private javax.swing.JLabel L_NombresSupervivientes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
