package apoocalipsis;
public class J_CrearPartida extends javax.swing.JFrame {

    /**
     * Creates new form J_CrearPartida
     */
    public J_CrearPartida() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B0_29 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        L_LogoURJC = new javax.swing.JLabel();
        B0_9 = new javax.swing.JButton();
        B0_11 = new javax.swing.JButton();
        B0_12 = new javax.swing.JButton();
        B0_13 = new javax.swing.JButton();
        B0_14 = new javax.swing.JButton();
        B0_15 = new javax.swing.JButton();
        B0_16 = new javax.swing.JButton();
        B0_17 = new javax.swing.JButton();
        B0_18 = new javax.swing.JButton();
        B0_19 = new javax.swing.JButton();
        B0_20 = new javax.swing.JButton();
        B0_21 = new javax.swing.JButton();
        B0_22 = new javax.swing.JButton();
        B0_23 = new javax.swing.JButton();
        B0_24 = new javax.swing.JButton();
        B0_25 = new javax.swing.JButton();
        B0_26 = new javax.swing.JButton();
        B0_27 = new javax.swing.JButton();
        B0_28 = new javax.swing.JButton();
        B0_30 = new javax.swing.JButton();
        B0_31 = new javax.swing.JButton();
        B0_32 = new javax.swing.JButton();
        B0_33 = new javax.swing.JButton();
        B0_34 = new javax.swing.JButton();
        B0_35 = new javax.swing.JButton();
        B0_36 = new javax.swing.JButton();
        B0_37 = new javax.swing.JButton();
        B0_38 = new javax.swing.JButton();
        B0_39 = new javax.swing.JButton();
        B0_40 = new javax.swing.JButton();
        B0_41 = new javax.swing.JButton();
        B0_42 = new javax.swing.JButton();
        B0_43 = new javax.swing.JButton();
        B0_44 = new javax.swing.JButton();
        B0_45 = new javax.swing.JButton();
        B0_46 = new javax.swing.JButton();
        B0_47 = new javax.swing.JButton();
        B0_48 = new javax.swing.JButton();
        B0_49 = new javax.swing.JButton();
        B0_50 = new javax.swing.JButton();
        B0_51 = new javax.swing.JButton();
        B0_52 = new javax.swing.JButton();
        B0_53 = new javax.swing.JButton();
        B0_54 = new javax.swing.JButton();
        B0_55 = new javax.swing.JButton();
        B0_56 = new javax.swing.JButton();
        B0_57 = new javax.swing.JButton();
        B0_58 = new javax.swing.JButton();
        B0_59 = new javax.swing.JButton();
        B0_60 = new javax.swing.JButton();
        B0_61 = new javax.swing.JButton();
        B0_62 = new javax.swing.JButton();
        B0_63 = new javax.swing.JButton();
        B0_64 = new javax.swing.JButton();
        B0_65 = new javax.swing.JButton();
        B0_66 = new javax.swing.JButton();
        B0_67 = new javax.swing.JButton();
        B0_68 = new javax.swing.JButton();
        B0_69 = new javax.swing.JButton();
        B0_70 = new javax.swing.JButton();
        B0_71 = new javax.swing.JButton();
        B0_72 = new javax.swing.JButton();
        B0_73 = new javax.swing.JButton();
        B0_74 = new javax.swing.JButton();
        B0_75 = new javax.swing.JButton();
        B0_76 = new javax.swing.JButton();
        B0_77 = new javax.swing.JButton();
        B0_78 = new javax.swing.JButton();
        B0_79 = new javax.swing.JButton();
        B0_80 = new javax.swing.JButton();
        B0_81 = new javax.swing.JButton();
        B0_82 = new javax.swing.JButton();
        B0_83 = new javax.swing.JButton();
        B0_84 = new javax.swing.JButton();
        B0_85 = new javax.swing.JButton();
        B0_86 = new javax.swing.JButton();
        B0_87 = new javax.swing.JButton();
        B0_88 = new javax.swing.JButton();
        B0_89 = new javax.swing.JButton();
        B0_90 = new javax.swing.JButton();
        B0_91 = new javax.swing.JButton();
        B0_92 = new javax.swing.JButton();
        B0_93 = new javax.swing.JButton();
        B0_94 = new javax.swing.JButton();
        B0_95 = new javax.swing.JButton();
        B0_96 = new javax.swing.JButton();
        B0_97 = new javax.swing.JButton();
        B0_98 = new javax.swing.JButton();
        B0_99 = new javax.swing.JButton();
        B0_100 = new javax.swing.JButton();
        B0_101 = new javax.swing.JButton();
        B0_102 = new javax.swing.JButton();
        B0_103 = new javax.swing.JButton();
        B0_104 = new javax.swing.JButton();
        B0_105 = new javax.swing.JButton();
        B0_106 = new javax.swing.JButton();
        B0_107 = new javax.swing.JButton();
        B0_108 = new javax.swing.JButton();
        B0_109 = new javax.swing.JButton();
        B0_110 = new javax.swing.JButton();

        B0_29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_29ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(253, 253, 253));

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));

        L_LogoURJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apoocalipsis/images/URJ_simbolo_POS_1.png"))); // NOI18N

        B0_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_9ActionPerformed(evt);
            }
        });

        B0_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_11ActionPerformed(evt);
            }
        });

        B0_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_12ActionPerformed(evt);
            }
        });

        B0_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_13ActionPerformed(evt);
            }
        });

        B0_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_14ActionPerformed(evt);
            }
        });

        B0_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_15ActionPerformed(evt);
            }
        });

        B0_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_16ActionPerformed(evt);
            }
        });

        B0_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_17ActionPerformed(evt);
            }
        });

        B0_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_18ActionPerformed(evt);
            }
        });

        B0_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_19ActionPerformed(evt);
            }
        });

        B0_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_20ActionPerformed(evt);
            }
        });

        B0_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_21ActionPerformed(evt);
            }
        });

        B0_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_22ActionPerformed(evt);
            }
        });

        B0_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_23ActionPerformed(evt);
            }
        });

        B0_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_24ActionPerformed(evt);
            }
        });

        B0_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_25ActionPerformed(evt);
            }
        });

        B0_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_26ActionPerformed(evt);
            }
        });

        B0_27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_27ActionPerformed(evt);
            }
        });

        B0_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_28ActionPerformed(evt);
            }
        });

        B0_30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_30ActionPerformed(evt);
            }
        });

        B0_31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_31ActionPerformed(evt);
            }
        });

        B0_32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_32ActionPerformed(evt);
            }
        });

        B0_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_33ActionPerformed(evt);
            }
        });

        B0_34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_34ActionPerformed(evt);
            }
        });

        B0_35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_35ActionPerformed(evt);
            }
        });

        B0_36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_36ActionPerformed(evt);
            }
        });

        B0_37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_37ActionPerformed(evt);
            }
        });

        B0_38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_38ActionPerformed(evt);
            }
        });

        B0_39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_39ActionPerformed(evt);
            }
        });

        B0_40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_40ActionPerformed(evt);
            }
        });

        B0_41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_41ActionPerformed(evt);
            }
        });

        B0_42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_42ActionPerformed(evt);
            }
        });

        B0_43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_43ActionPerformed(evt);
            }
        });

        B0_44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_44ActionPerformed(evt);
            }
        });

        B0_45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_45ActionPerformed(evt);
            }
        });

        B0_46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_46ActionPerformed(evt);
            }
        });

        B0_47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_47ActionPerformed(evt);
            }
        });

        B0_48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_48ActionPerformed(evt);
            }
        });

        B0_49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_49ActionPerformed(evt);
            }
        });

        B0_50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_50ActionPerformed(evt);
            }
        });

        B0_51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_51ActionPerformed(evt);
            }
        });

        B0_52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_52ActionPerformed(evt);
            }
        });

        B0_53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_53ActionPerformed(evt);
            }
        });

        B0_54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_54ActionPerformed(evt);
            }
        });

        B0_55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_55ActionPerformed(evt);
            }
        });

        B0_56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_56ActionPerformed(evt);
            }
        });

        B0_57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_57ActionPerformed(evt);
            }
        });

        B0_58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_58ActionPerformed(evt);
            }
        });

        B0_59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_59ActionPerformed(evt);
            }
        });

        B0_60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_60ActionPerformed(evt);
            }
        });

        B0_61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_61ActionPerformed(evt);
            }
        });

        B0_62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_62ActionPerformed(evt);
            }
        });

        B0_63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_63ActionPerformed(evt);
            }
        });

        B0_64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_64ActionPerformed(evt);
            }
        });

        B0_65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_65ActionPerformed(evt);
            }
        });

        B0_66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_66ActionPerformed(evt);
            }
        });

        B0_67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_67ActionPerformed(evt);
            }
        });

        B0_68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_68ActionPerformed(evt);
            }
        });

        B0_69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_69ActionPerformed(evt);
            }
        });

        B0_70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_70ActionPerformed(evt);
            }
        });

        B0_71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_71ActionPerformed(evt);
            }
        });

        B0_72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_72ActionPerformed(evt);
            }
        });

        B0_73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_73ActionPerformed(evt);
            }
        });

        B0_74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_74ActionPerformed(evt);
            }
        });

        B0_75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_75ActionPerformed(evt);
            }
        });

        B0_76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_76ActionPerformed(evt);
            }
        });

        B0_77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_77ActionPerformed(evt);
            }
        });

        B0_78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_78ActionPerformed(evt);
            }
        });

        B0_79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_79ActionPerformed(evt);
            }
        });

        B0_80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_80ActionPerformed(evt);
            }
        });

        B0_81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_81ActionPerformed(evt);
            }
        });

        B0_82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_82ActionPerformed(evt);
            }
        });

        B0_83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_83ActionPerformed(evt);
            }
        });

        B0_84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_84ActionPerformed(evt);
            }
        });

        B0_85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_85ActionPerformed(evt);
            }
        });

        B0_86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_86ActionPerformed(evt);
            }
        });

        B0_87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_87ActionPerformed(evt);
            }
        });

        B0_88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_88ActionPerformed(evt);
            }
        });

        B0_89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_89ActionPerformed(evt);
            }
        });

        B0_90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_90ActionPerformed(evt);
            }
        });

        B0_91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_91ActionPerformed(evt);
            }
        });

        B0_92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_92ActionPerformed(evt);
            }
        });

        B0_93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_93ActionPerformed(evt);
            }
        });

        B0_94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_94ActionPerformed(evt);
            }
        });

        B0_95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_95ActionPerformed(evt);
            }
        });

        B0_96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_96ActionPerformed(evt);
            }
        });

        B0_97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_97ActionPerformed(evt);
            }
        });

        B0_98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_98ActionPerformed(evt);
            }
        });

        B0_99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_99ActionPerformed(evt);
            }
        });

        B0_100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_100ActionPerformed(evt);
            }
        });

        B0_101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_101ActionPerformed(evt);
            }
        });

        B0_102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_102ActionPerformed(evt);
            }
        });

        B0_103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_103ActionPerformed(evt);
            }
        });

        B0_104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_104ActionPerformed(evt);
            }
        });

        B0_105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_105ActionPerformed(evt);
            }
        });

        B0_106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_106ActionPerformed(evt);
            }
        });

        B0_107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_107ActionPerformed(evt);
            }
        });

        B0_108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_108ActionPerformed(evt);
            }
        });

        B0_109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_109ActionPerformed(evt);
            }
        });

        B0_110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0_110ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B0_18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_103, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_104, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_105, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_106, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_108, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_109, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B0_110, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 732, Short.MAX_VALUE)
                        .addComponent(L_LogoURJC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_79, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_82, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_83, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_84, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_86, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_88, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_89, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_59, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_60, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_90, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_91, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_92, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_93, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_94, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_95, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_96, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_97, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_69, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_70, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_107, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_98, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_99, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_100, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_101, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_102, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_77, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_80, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B0_21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B0_75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_LogoURJC)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(B0_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(B0_21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B0_30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(B0_31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B0_75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(B0_28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B0_11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_77, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_80, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(B0_12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(B0_44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(B0_46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_79, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0_81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(B0_36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(B0_13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B0_82, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(B0_83, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B0_84, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B0_85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B0_86, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B0_87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B0_88, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B0_89, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(B0_37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B0_17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_90, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_91, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_92, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_93, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_94, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_95, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_96, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_97, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(B0_14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B0_73, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(B0_59, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_60, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0_65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(B0_39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B0_15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_69, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_70, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B0_16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_107, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_98, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_99, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_100, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_101, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_102, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B0_18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_103, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_104, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_105, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_106, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_108, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_109, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0_110, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B0_29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_29ActionPerformed

    private void B0_110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_110ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_110ActionPerformed

    private void B0_109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_109ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_109ActionPerformed

    private void B0_108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_108ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_108ActionPerformed

    private void B0_107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_107ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_107ActionPerformed

    private void B0_106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_106ActionPerformed

    private void B0_105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_105ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_105ActionPerformed

    private void B0_104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_104ActionPerformed

    private void B0_103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_103ActionPerformed

    private void B0_102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_102ActionPerformed

    private void B0_101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_101ActionPerformed

    private void B0_100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_100ActionPerformed

    private void B0_99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_99ActionPerformed

    private void B0_98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_98ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_98ActionPerformed

    private void B0_97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_97ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_97ActionPerformed

    private void B0_96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_96ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_96ActionPerformed

    private void B0_95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_95ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_95ActionPerformed

    private void B0_94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_94ActionPerformed

    private void B0_93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_93ActionPerformed

    private void B0_92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_92ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_92ActionPerformed

    private void B0_91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_91ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_91ActionPerformed

    private void B0_90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_90ActionPerformed

    private void B0_89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_89ActionPerformed

    private void B0_88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_88ActionPerformed

    private void B0_87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_87ActionPerformed

    private void B0_86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_86ActionPerformed

    private void B0_85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_85ActionPerformed

    private void B0_84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_84ActionPerformed

    private void B0_83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_83ActionPerformed

    private void B0_82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_82ActionPerformed

    private void B0_81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_81ActionPerformed

    private void B0_80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_80ActionPerformed

    private void B0_79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_79ActionPerformed

    private void B0_78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_78ActionPerformed

    private void B0_77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_77ActionPerformed

    private void B0_76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_76ActionPerformed

    private void B0_75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_75ActionPerformed

    private void B0_74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_74ActionPerformed

    private void B0_73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_73ActionPerformed

    private void B0_72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_72ActionPerformed

    private void B0_71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_71ActionPerformed

    private void B0_70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_70ActionPerformed

    private void B0_69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_69ActionPerformed

    private void B0_68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_68ActionPerformed

    private void B0_67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_67ActionPerformed

    private void B0_66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_66ActionPerformed

    private void B0_65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_65ActionPerformed

    private void B0_64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_64ActionPerformed

    private void B0_63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_63ActionPerformed

    private void B0_62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_62ActionPerformed

    private void B0_61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_61ActionPerformed

    private void B0_60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_60ActionPerformed

    private void B0_59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_59ActionPerformed

    private void B0_58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_58ActionPerformed

    private void B0_57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_57ActionPerformed

    private void B0_56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_56ActionPerformed

    private void B0_55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_55ActionPerformed

    private void B0_54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_54ActionPerformed

    private void B0_53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_53ActionPerformed

    private void B0_52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_52ActionPerformed

    private void B0_51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_51ActionPerformed

    private void B0_50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_50ActionPerformed

    private void B0_49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_49ActionPerformed

    private void B0_48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_48ActionPerformed

    private void B0_47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_47ActionPerformed

    private void B0_46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_46ActionPerformed

    private void B0_45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_45ActionPerformed

    private void B0_44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_44ActionPerformed

    private void B0_43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_43ActionPerformed

    private void B0_42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_42ActionPerformed

    private void B0_41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_41ActionPerformed

    private void B0_40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_40ActionPerformed

    private void B0_39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_39ActionPerformed

    private void B0_38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_38ActionPerformed

    private void B0_37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_37ActionPerformed

    private void B0_36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_36ActionPerformed

    private void B0_35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_35ActionPerformed

    private void B0_34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_34ActionPerformed

    private void B0_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_33ActionPerformed

    private void B0_32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_32ActionPerformed

    private void B0_31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_31ActionPerformed

    private void B0_30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_30ActionPerformed

    private void B0_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_28ActionPerformed

    private void B0_27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_27ActionPerformed

    private void B0_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_26ActionPerformed

    private void B0_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_25ActionPerformed

    private void B0_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_24ActionPerformed

    private void B0_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_23ActionPerformed

    private void B0_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_22ActionPerformed

    private void B0_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_21ActionPerformed

    private void B0_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_20ActionPerformed

    private void B0_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_19ActionPerformed

    private void B0_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_18ActionPerformed

    private void B0_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_17ActionPerformed

    private void B0_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_16ActionPerformed

    private void B0_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_15ActionPerformed

    private void B0_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_14ActionPerformed

    private void B0_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_13ActionPerformed

    private void B0_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_12ActionPerformed

    private void B0_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_11ActionPerformed

    private void B0_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0_9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J_CrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J_CrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J_CrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J_CrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J_CrearPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0_100;
    private javax.swing.JButton B0_101;
    private javax.swing.JButton B0_102;
    private javax.swing.JButton B0_103;
    private javax.swing.JButton B0_104;
    private javax.swing.JButton B0_105;
    private javax.swing.JButton B0_106;
    private javax.swing.JButton B0_107;
    private javax.swing.JButton B0_108;
    private javax.swing.JButton B0_109;
    private javax.swing.JButton B0_11;
    private javax.swing.JButton B0_110;
    private javax.swing.JButton B0_12;
    private javax.swing.JButton B0_13;
    private javax.swing.JButton B0_14;
    private javax.swing.JButton B0_15;
    private javax.swing.JButton B0_16;
    private javax.swing.JButton B0_17;
    private javax.swing.JButton B0_18;
    private javax.swing.JButton B0_19;
    private javax.swing.JButton B0_20;
    private javax.swing.JButton B0_21;
    private javax.swing.JButton B0_22;
    private javax.swing.JButton B0_23;
    private javax.swing.JButton B0_24;
    private javax.swing.JButton B0_25;
    private javax.swing.JButton B0_26;
    private javax.swing.JButton B0_27;
    private javax.swing.JButton B0_28;
    private javax.swing.JButton B0_29;
    private javax.swing.JButton B0_30;
    private javax.swing.JButton B0_31;
    private javax.swing.JButton B0_32;
    private javax.swing.JButton B0_33;
    private javax.swing.JButton B0_34;
    private javax.swing.JButton B0_35;
    private javax.swing.JButton B0_36;
    private javax.swing.JButton B0_37;
    private javax.swing.JButton B0_38;
    private javax.swing.JButton B0_39;
    private javax.swing.JButton B0_40;
    private javax.swing.JButton B0_41;
    private javax.swing.JButton B0_42;
    private javax.swing.JButton B0_43;
    private javax.swing.JButton B0_44;
    private javax.swing.JButton B0_45;
    private javax.swing.JButton B0_46;
    private javax.swing.JButton B0_47;
    private javax.swing.JButton B0_48;
    private javax.swing.JButton B0_49;
    private javax.swing.JButton B0_50;
    private javax.swing.JButton B0_51;
    private javax.swing.JButton B0_52;
    private javax.swing.JButton B0_53;
    private javax.swing.JButton B0_54;
    private javax.swing.JButton B0_55;
    private javax.swing.JButton B0_56;
    private javax.swing.JButton B0_57;
    private javax.swing.JButton B0_58;
    private javax.swing.JButton B0_59;
    private javax.swing.JButton B0_60;
    private javax.swing.JButton B0_61;
    private javax.swing.JButton B0_62;
    private javax.swing.JButton B0_63;
    private javax.swing.JButton B0_64;
    private javax.swing.JButton B0_65;
    private javax.swing.JButton B0_66;
    private javax.swing.JButton B0_67;
    private javax.swing.JButton B0_68;
    private javax.swing.JButton B0_69;
    private javax.swing.JButton B0_70;
    private javax.swing.JButton B0_71;
    private javax.swing.JButton B0_72;
    private javax.swing.JButton B0_73;
    private javax.swing.JButton B0_74;
    private javax.swing.JButton B0_75;
    private javax.swing.JButton B0_76;
    private javax.swing.JButton B0_77;
    private javax.swing.JButton B0_78;
    private javax.swing.JButton B0_79;
    private javax.swing.JButton B0_80;
    private javax.swing.JButton B0_81;
    private javax.swing.JButton B0_82;
    private javax.swing.JButton B0_83;
    private javax.swing.JButton B0_84;
    private javax.swing.JButton B0_85;
    private javax.swing.JButton B0_86;
    private javax.swing.JButton B0_87;
    private javax.swing.JButton B0_88;
    private javax.swing.JButton B0_89;
    private javax.swing.JButton B0_9;
    private javax.swing.JButton B0_90;
    private javax.swing.JButton B0_91;
    private javax.swing.JButton B0_92;
    private javax.swing.JButton B0_93;
    private javax.swing.JButton B0_94;
    private javax.swing.JButton B0_95;
    private javax.swing.JButton B0_96;
    private javax.swing.JButton B0_97;
    private javax.swing.JButton B0_98;
    private javax.swing.JButton B0_99;
    private javax.swing.JLabel L_LogoURJC;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
