package apoocalipsis;
/**
 *
 * @author Anass Chikou El Mahraoui, Edward Andrei, Manuel Alos de la Vega
 */
public class J_DatosAtaqueAislado extends javax.swing.JPanel {

    /**
     * Creates new form J_DatosAtaqueAislado
     */
    public J_DatosAtaqueAislado() {
        initComponents();
        Arma a = new Arma();
        for (String s : a.getNombresArma()) {
            cbNombreArma.addItem(s);
        }
        for (int i=0; i<=a.getMaxAlcance(); i++) {
            String s = i + "";
            cbAlcanceArma.addItem(s);
        }
        for (int i : a.getValoresPotencia()) {
            String s = i + "";
            cbPotenciaArma.addItem(s);
        }
        for (int i : a.getValoresDado()) {
            String s = i + "";
            cbValorExitoArma.addItem(s);
        }
        for (int i=0; i<=a.getValoresExito(); i++) {
            String s = i + "";
            cbNumDadosArma.addItem(s);
        }
    }
    
    public String getNombreArma() { return (String)cbNombreArma.getSelectedItem(); }
    public int getAlcanceArma() {
        return Integer.parseInt((String)cbAlcanceArma.getSelectedItem());
    }
    public int getPotenciaArma() {
        return Integer.parseInt((String)cbPotenciaArma.getSelectedItem());
    }
    public int getNumDadosArma() {
        return Integer.parseInt((String)cbNumDadosArma.getSelectedItem());
    }
    public int getValorExitoArma() {
        return Integer.parseInt((String)cbValorExitoArma.getSelectedItem());
    }
    public int getSupX() {
        try {
            return Integer.parseInt((String)tfSupX.getText());
        } catch(NumberFormatException e) {
            return -1;
        }
    }
    public int getSupY() {
        try {
            return Integer.parseInt((String)tfSupY.getText());
        } catch(NumberFormatException e) {
            return -1;
        }
    }
    public int getZombiX() {
        try {
            return Integer.parseInt((String)tfZombiX.getText());
        } catch(NumberFormatException e) {
            return -1;
        }
    }
    public int getZombiY() {
        try {
            return Integer.parseInt((String)tfZombiY.getText());
        } catch(NumberFormatException e) {
            return -1;
        }
    }
    public String getTipoZombi() { return (String)cbTipoZombi.getSelectedItem(); }
    
    public void setTiposZombi(String [] tipos) {
        for (String s : tipos) {
            cbTipoZombi.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        L_NombreSuperviviente5 = new javax.swing.JLabel();
        L_NombreSuperviviente4 = new javax.swing.JLabel();
        L_NombreSuperviviente6 = new javax.swing.JLabel();
        L_NombreSuperviviente7 = new javax.swing.JLabel();
        L_NombreSuperviviente8 = new javax.swing.JLabel();
        L_NombreSuperviviente9 = new javax.swing.JLabel();
        L_NombreSuperviviente10 = new javax.swing.JLabel();
        L_NombreSuperviviente11 = new javax.swing.JLabel();
        cbTipoZombi = new javax.swing.JComboBox<>();
        tfSupX = new javax.swing.JTextField();
        tfSupY = new javax.swing.JTextField();
        tfZombiX = new javax.swing.JTextField();
        tfZombiY = new javax.swing.JTextField();
        L_NombreSuperviviente13 = new javax.swing.JLabel();
        L_NombreSuperviviente14 = new javax.swing.JLabel();
        L_NombreSuperviviente16 = new javax.swing.JLabel();
        cbNombreArma = new javax.swing.JComboBox<>();
        cbAlcanceArma = new javax.swing.JComboBox<>();
        cbPotenciaArma = new javax.swing.JComboBox<>();
        L_NombreSuperviviente15 = new javax.swing.JLabel();
        L_NombreSuperviviente17 = new javax.swing.JLabel();
        cbNumDadosArma = new javax.swing.JComboBox<>();
        cbValorExitoArma = new javax.swing.JComboBox<>();
        L_NombreSuperviviente18 = new javax.swing.JLabel();
        L_LogoURJC = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setBackground(new java.awt.Color(253, 253, 253));

        L_NombreSuperviviente5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        L_NombreSuperviviente5.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente5.setText("Elige los datos del zombi el superviviente y su arma");

        L_NombreSuperviviente4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente4.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente4.setText("Superviviente");

        L_NombreSuperviviente6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente6.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente6.setText("X:");

        L_NombreSuperviviente7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente7.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente7.setText("Y:");

        L_NombreSuperviviente8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente8.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente8.setText("Zombi");

        L_NombreSuperviviente9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente9.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente9.setText("X:");

        L_NombreSuperviviente10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente10.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente10.setText("Y:");

        L_NombreSuperviviente11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente11.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente11.setText("Tipo:");

        cbTipoZombi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoZombiActionPerformed(evt);
            }
        });

        tfSupX.setText("0");
        tfSupX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSupXActionPerformed(evt);
            }
        });

        tfSupY.setText("0");

        tfZombiX.setText("0");

        tfZombiY.setText("0");

        L_NombreSuperviviente13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente13.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente13.setText("Arma");

        L_NombreSuperviviente14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente14.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente14.setText("Nombre:");

        L_NombreSuperviviente16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente16.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente16.setText("Alcance:");

        L_NombreSuperviviente15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente15.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente15.setText("Potencia:");

        L_NombreSuperviviente17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente17.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente17.setText("Numero de dados:");

        L_NombreSuperviviente18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_NombreSuperviviente18.setForeground(new java.awt.Color(7, 33, 68));
        L_NombreSuperviviente18.setText("Valor de exito:");

        L_LogoURJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apoocalipsis/image/URJ_simbolo_POS_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L_LogoURJC)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_NombreSuperviviente4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_NombreSuperviviente6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfSupX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_NombreSuperviviente7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfSupY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_NombreSuperviviente10)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfZombiY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_NombreSuperviviente9)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfZombiX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(L_NombreSuperviviente11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbTipoZombi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(L_NombreSuperviviente8)))
                            .addComponent(L_NombreSuperviviente5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbNombreArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbAlcanceArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNumDadosArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L_NombreSuperviviente15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPotenciaArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(L_NombreSuperviviente18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbValorExitoArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_NombreSuperviviente13)
                        .addGap(325, 325, 325)))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(L_NombreSuperviviente5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoZombi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSupX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfZombiX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSupY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfZombiY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(L_NombreSuperviviente13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNombreArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPotenciaArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbValorExitoArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NombreSuperviviente16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NombreSuperviviente17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlcanceArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNumDadosArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(L_LogoURJC)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfSupXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSupXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSupXActionPerformed

    private void cbTipoZombiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoZombiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoZombiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_LogoURJC;
    private javax.swing.JLabel L_NombreSuperviviente10;
    private javax.swing.JLabel L_NombreSuperviviente11;
    private javax.swing.JLabel L_NombreSuperviviente13;
    private javax.swing.JLabel L_NombreSuperviviente14;
    private javax.swing.JLabel L_NombreSuperviviente15;
    private javax.swing.JLabel L_NombreSuperviviente16;
    private javax.swing.JLabel L_NombreSuperviviente17;
    private javax.swing.JLabel L_NombreSuperviviente18;
    private javax.swing.JLabel L_NombreSuperviviente4;
    private javax.swing.JLabel L_NombreSuperviviente5;
    private javax.swing.JLabel L_NombreSuperviviente6;
    private javax.swing.JLabel L_NombreSuperviviente7;
    private javax.swing.JLabel L_NombreSuperviviente8;
    private javax.swing.JLabel L_NombreSuperviviente9;
    private javax.swing.JComboBox<String> cbAlcanceArma;
    private javax.swing.JComboBox<String> cbNombreArma;
    private javax.swing.JComboBox<String> cbNumDadosArma;
    private javax.swing.JComboBox<String> cbPotenciaArma;
    private javax.swing.JComboBox<String> cbTipoZombi;
    private javax.swing.JComboBox<String> cbValorExitoArma;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField tfSupX;
    private javax.swing.JTextField tfSupY;
    private javax.swing.JTextField tfZombiX;
    private javax.swing.JTextField tfZombiY;
    // End of variables declaration//GEN-END:variables
}
