/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apoocalipsis;

import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class J_Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public J_Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b00 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        b03 = new javax.swing.JButton();
        b04 = new javax.swing.JButton();
        b05 = new javax.swing.JButton();
        b06 = new javax.swing.JButton();
        b07 = new javax.swing.JButton();
        b08 = new javax.swing.JButton();
        b09 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b37 = new javax.swing.JButton();
        b38 = new javax.swing.JButton();
        b39 = new javax.swing.JButton();
        b40 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        b45 = new javax.swing.JButton();
        b46 = new javax.swing.JButton();
        b47 = new javax.swing.JButton();
        b48 = new javax.swing.JButton();
        b49 = new javax.swing.JButton();
        b50 = new javax.swing.JButton();
        b51 = new javax.swing.JButton();
        b52 = new javax.swing.JButton();
        b53 = new javax.swing.JButton();
        b54 = new javax.swing.JButton();
        b55 = new javax.swing.JButton();
        b56 = new javax.swing.JButton();
        b57 = new javax.swing.JButton();
        b58 = new javax.swing.JButton();
        b59 = new javax.swing.JButton();
        b60 = new javax.swing.JButton();
        b61 = new javax.swing.JButton();
        b62 = new javax.swing.JButton();
        b63 = new javax.swing.JButton();
        b64 = new javax.swing.JButton();
        b65 = new javax.swing.JButton();
        b66 = new javax.swing.JButton();
        b67 = new javax.swing.JButton();
        b68 = new javax.swing.JButton();
        b69 = new javax.swing.JButton();
        b70 = new javax.swing.JButton();
        b71 = new javax.swing.JButton();
        b72 = new javax.swing.JButton();
        b73 = new javax.swing.JButton();
        b74 = new javax.swing.JButton();
        b75 = new javax.swing.JButton();
        b76 = new javax.swing.JButton();
        b77 = new javax.swing.JButton();
        b78 = new javax.swing.JButton();
        b79 = new javax.swing.JButton();
        b80 = new javax.swing.JButton();
        b81 = new javax.swing.JButton();
        b82 = new javax.swing.JButton();
        b83 = new javax.swing.JButton();
        b84 = new javax.swing.JButton();
        b85 = new javax.swing.JButton();
        b86 = new javax.swing.JButton();
        b87 = new javax.swing.JButton();
        b88 = new javax.swing.JButton();
        b89 = new javax.swing.JButton();
        b90 = new javax.swing.JButton();
        b91 = new javax.swing.JButton();
        b92 = new javax.swing.JButton();
        b93 = new javax.swing.JButton();
        b94 = new javax.swing.JButton();
        b95 = new javax.swing.JButton();
        b96 = new javax.swing.JButton();
        b97 = new javax.swing.JButton();
        b98 = new javax.swing.JButton();
        b99 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        B_Salir = new javax.swing.JButton();
        L_LogoURJC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(253, 253, 253));

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));
        jPanel1.setLayout(new java.awt.GridLayout(10, 10, 10, 10));

        b00.setText("jButton1");
        b00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b00ActionPerformed(evt);
            }
        });
        jPanel1.add(b00);

        b01.setText("jButton7");
        jPanel1.add(b01);

        b02.setText("jButton6");
        jPanel1.add(b02);

        b03.setText("jButton2");
        jPanel1.add(b03);

        b04.setText("jButton4");
        jPanel1.add(b04);

        b05.setText("jButton10");
        jPanel1.add(b05);

        b06.setText("jButton9");
        jPanel1.add(b06);

        b07.setText("jButton13");
        jPanel1.add(b07);

        b08.setText("jButton8");
        jPanel1.add(b08);

        b09.setText("jButton1");
        jPanel1.add(b09);

        b10.setText("jButton20");
        jPanel1.add(b10);

        b11.setText("jButton5");
        jPanel1.add(b11);

        b12.setText("jButton19");
        jPanel1.add(b12);

        b13.setText("jButton17");
        jPanel1.add(b13);

        b14.setText("jButton21");
        jPanel1.add(b14);

        b15.setText("jButton23");
        jPanel1.add(b15);

        b16.setText("jButton3");
        jPanel1.add(b16);

        b17.setText("jButton30");
        jPanel1.add(b17);

        b18.setText("jButton28");
        jPanel1.add(b18);

        b19.setText("jButton43");
        jPanel1.add(b19);

        b20.setText("jButton46");
        jPanel1.add(b20);

        b21.setText("jButton38");
        jPanel1.add(b21);

        b22.setText("jButton59");
        jPanel1.add(b22);

        b23.setText("jButton60");
        jPanel1.add(b23);

        b24.setText("jButton57");
        jPanel1.add(b24);

        b25.setText("jButton69");
        jPanel1.add(b25);

        b26.setText("jButton58");
        jPanel1.add(b26);

        b27.setText("jButton68");
        jPanel1.add(b27);

        b28.setText("jButton63");
        jPanel1.add(b28);

        b29.setText("jButton67");
        jPanel1.add(b29);

        b30.setText("jButton79");
        jPanel1.add(b30);

        b31.setText("jButton73");
        jPanel1.add(b31);

        b32.setText("jButton76");
        jPanel1.add(b32);

        b33.setText("jButton72");
        jPanel1.add(b33);

        b34.setText("jButton71");
        jPanel1.add(b34);

        b35.setText("jButton81");
        jPanel1.add(b35);

        b36.setText("jButton93");
        jPanel1.add(b36);

        b37.setText("jButton66");
        jPanel1.add(b37);

        b38.setText("jButton92");
        jPanel1.add(b38);

        b39.setText("jButton64");
        jPanel1.add(b39);

        b40.setText("jButton80");
        jPanel1.add(b40);

        b41.setText("jButton37");
        jPanel1.add(b41);

        b42.setText("jButton70");
        jPanel1.add(b42);

        b43.setText("jButton74");
        jPanel1.add(b43);

        b44.setText("jButton77");
        jPanel1.add(b44);

        b45.setText("jButton89");
        jPanel1.add(b45);

        b46.setText("jButton94");
        jPanel1.add(b46);

        b47.setText("jButton100");
        jPanel1.add(b47);

        b48.setText("jButton95");
        jPanel1.add(b48);

        b49.setText("jButton99");
        jPanel1.add(b49);

        b50.setText("jButton98");
        jPanel1.add(b50);

        b51.setText("jButton75");
        jPanel1.add(b51);

        b52.setText("jButton82");
        jPanel1.add(b52);

        b53.setText("jButton61");
        jPanel1.add(b53);

        b54.setText("jButton54");
        jPanel1.add(b54);

        b55.setText("jButton56");
        jPanel1.add(b55);

        b56.setText("jButton36");
        jPanel1.add(b56);

        b57.setText("jButton50");
        jPanel1.add(b57);

        b58.setText("jButton85");
        jPanel1.add(b58);

        b59.setText("jButton78");
        jPanel1.add(b59);

        b60.setText("jButton97");
        jPanel1.add(b60);

        b61.setText("jButton90");
        jPanel1.add(b61);

        b62.setText("jButton96");
        jPanel1.add(b62);

        b63.setText("jButton86");
        jPanel1.add(b63);

        b64.setText("jButton88");
        jPanel1.add(b64);

        b65.setText("jButton65");
        jPanel1.add(b65);

        b66.setText("jButton91");
        jPanel1.add(b66);

        b67.setText("jButton84");
        jPanel1.add(b67);

        b68.setText("jButton62");
        jPanel1.add(b68);

        b69.setText("jButton48");
        jPanel1.add(b69);

        b70.setText("jButton32");
        jPanel1.add(b70);

        b71.setText("jButton45");
        jPanel1.add(b71);

        b72.setText("jButton55");
        jPanel1.add(b72);

        b73.setText("jButton87");
        jPanel1.add(b73);

        b74.setText("jButton52");
        jPanel1.add(b74);

        b75.setText("jButton53");
        jPanel1.add(b75);

        b76.setText("jButton44");
        jPanel1.add(b76);

        b77.setText("jButton51");
        jPanel1.add(b77);

        b78.setText("jButton39");
        jPanel1.add(b78);

        b79.setText("jButton83");
        jPanel1.add(b79);

        b80.setText("jButton49");
        jPanel1.add(b80);

        b81.setText("jButton12");
        jPanel1.add(b81);

        b82.setText("jButton47");
        jPanel1.add(b82);

        b83.setText("jButton25");
        jPanel1.add(b83);

        b84.setText("jButton29");
        jPanel1.add(b84);

        b85.setText("jButton24");
        jPanel1.add(b85);

        b86.setText("jButton42");
        jPanel1.add(b86);

        b87.setText("jButton40");
        jPanel1.add(b87);

        b88.setText("jButton41");
        jPanel1.add(b88);

        b89.setText("jButton27");
        jPanel1.add(b89);

        b90.setText("jButton26");
        jPanel1.add(b90);

        b91.setText("jButton16");
        jPanel1.add(b91);

        b92.setText("jButton35");
        jPanel1.add(b92);

        b93.setText("jButton33");
        jPanel1.add(b93);

        b94.setText("jButton18");
        jPanel1.add(b94);

        b95.setText("jButton14");
        jPanel1.add(b95);

        b96.setText("jButton31");
        jPanel1.add(b96);

        b97.setText("jButton34");
        jPanel1.add(b97);

        b98.setText("jButton22");
        jPanel1.add(b98);

        b99.setText("jButton11");
        jPanel1.add(b99);

        jPanel2.setBackground(new java.awt.Color(253, 253, 253));
        jPanel2.setLayout(new java.awt.CardLayout());

        B_Salir.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        B_Salir.setForeground(new java.awt.Color(255, 51, 0));
        B_Salir.setText("SALIR");
        B_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SalirActionPerformed(evt);
            }
        });

        L_LogoURJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apoocalipsis/images/URJ_simbolo_POS_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 652, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(L_LogoURJC))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(B_Salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 673, Short.MAX_VALUE)
                        .addComponent(L_LogoURJC))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b00ActionPerformed

    private void B_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SalirActionPerformed
            // Mostrar un cuadro de confirmación
        int opcion = JOptionPane.showConfirmDialog(this, 
                                                    "¿Estás seguro de que quieres salir?", 
                                                    "Confirmar salida", 
                                                    JOptionPane.YES_NO_OPTION, 
                                                    JOptionPane.QUESTION_MESSAGE);

        // Si el usuario elige "Sí", cerrar el programa
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_B_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J_Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Salir;
    private javax.swing.JLabel L_LogoURJC;
    private javax.swing.JButton b00;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b03;
    private javax.swing.JButton b04;
    private javax.swing.JButton b05;
    private javax.swing.JButton b06;
    private javax.swing.JButton b07;
    private javax.swing.JButton b08;
    private javax.swing.JButton b09;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JButton b37;
    private javax.swing.JButton b38;
    private javax.swing.JButton b39;
    private javax.swing.JButton b40;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton b43;
    private javax.swing.JButton b44;
    private javax.swing.JButton b45;
    private javax.swing.JButton b46;
    private javax.swing.JButton b47;
    private javax.swing.JButton b48;
    private javax.swing.JButton b49;
    private javax.swing.JButton b50;
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JButton b53;
    private javax.swing.JButton b54;
    private javax.swing.JButton b55;
    private javax.swing.JButton b56;
    private javax.swing.JButton b57;
    private javax.swing.JButton b58;
    private javax.swing.JButton b59;
    private javax.swing.JButton b60;
    private javax.swing.JButton b61;
    private javax.swing.JButton b62;
    private javax.swing.JButton b63;
    private javax.swing.JButton b64;
    private javax.swing.JButton b65;
    private javax.swing.JButton b66;
    private javax.swing.JButton b67;
    private javax.swing.JButton b68;
    private javax.swing.JButton b69;
    private javax.swing.JButton b70;
    private javax.swing.JButton b71;
    private javax.swing.JButton b72;
    private javax.swing.JButton b73;
    private javax.swing.JButton b74;
    private javax.swing.JButton b75;
    private javax.swing.JButton b76;
    private javax.swing.JButton b77;
    private javax.swing.JButton b78;
    private javax.swing.JButton b79;
    private javax.swing.JButton b80;
    private javax.swing.JButton b81;
    private javax.swing.JButton b82;
    private javax.swing.JButton b83;
    private javax.swing.JButton b84;
    private javax.swing.JButton b85;
    private javax.swing.JButton b86;
    private javax.swing.JButton b87;
    private javax.swing.JButton b88;
    private javax.swing.JButton b89;
    private javax.swing.JButton b90;
    private javax.swing.JButton b91;
    private javax.swing.JButton b92;
    private javax.swing.JButton b93;
    private javax.swing.JButton b94;
    private javax.swing.JButton b95;
    private javax.swing.JButton b96;
    private javax.swing.JButton b97;
    private javax.swing.JButton b98;
    private javax.swing.JButton b99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
